# Каталог тренировок
GET http://localhost:4000/api/training/catalog?price=10,4000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODQ4OTE3NCwiZXhwIjoxNjg4NDkwMDc0fQ.ohW4XQL9X1a4wsKO1gibEKT7L2WSZ79kIMo4wWkFVsw
###

# Добавить комментарий
POST http://localhost:4000/api/training/comments/create/64a406e9c4d605ea3e822df6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODQ4OTE3NCwiZXhwIjoxNjg4NDkwMDc0fQ.ohW4XQL9X1a4wsKO1gibEKT7L2WSZ79kIMo4wWkFVsw
Content-Type: application/json

{
  "message": "Very good",
  "rating": 10
}
###

# Список комментариев
GET http://localhost:4000/api/training/comments/64a406e9c4d605ea3e822df6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODQ4OTE3NCwiZXhwIjoxNjg4NDkwMDc0fQ.ohW4XQL9X1a4wsKO1gibEKT7L2WSZ79kIMo4wWkFVsw
###
