# Создание тренировки
POST http://localhost:4000/api/coach/training/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGE0NDI4N2MwOTZiNThlODE1NTFlMmQiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCc0LjRhdCw0LnQu9C-0LLQsCDQldC70LXQvdCwIiwiaWF0IjoxNjg4NDg3Nzk2LCJleHAiOjE2ODg0ODg2OTZ9.dH3fE5bB82T-hgpZiBQwfHVgZQN4unX3CZSJrmZg7Yw
Content-Type: application/json

{
  "title": "Training",
  "level": "Professional",
  "trainingStyle": "Crossfit",
  "trainingTime": "30-50 мин",
  "price": 2400,
  "caloriesLoss": 3000,
  "description": "Тренировка кроссфит",
  "gender": "Female",
  "isSpecial": true
}
###
# Редактирование  тренировки
POST http://localhost:4000/api/coach/training/edit/64a447e28cc4fa6456f411fa HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGE0NDI4N2MwOTZiNThlODE1NTFlMmQiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCc0LjRhdCw0LnQu9C-0LLQsCDQldC70LXQvdCwIiwiaWF0IjoxNjg4NDg3Nzk2LCJleHAiOjE2ODg0ODg2OTZ9.dH3fE5bB82T-hgpZiBQwfHVgZQN4unX3CZSJrmZg7Yw
Content-Type: application/json

{
  "price": 2700
}
###
# Детальная информация о тренировке
GET http://localhost:4000/api/coach/training/64a406e9c4d605ea3e822df6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGE0NDI4N2MwOTZiNThlODE1NTFlMmQiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCc0LjRhdCw0LnQu9C-0LLQsCDQldC70LXQvdCwIiwiaWF0IjoxNjg4NDg3Nzk2LCJleHAiOjE2ODg0ODg2OTZ9.dH3fE5bB82T-hgpZiBQwfHVgZQN4unX3CZSJrmZg7Yw
Content-Type: application/json
###

# Список тренировок
GET http://localhost:4000/api/coach/training/show/list?price=10,3000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6ImNvYWNoMkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsInVzZXJOYW1lIjoi0J3QuNC60L7Qu9Cw0LXQstCwINCV0LvQtdC90LAiLCJpYXQiOjE2ODg0ODgyODUsImV4cCI6MTY4ODQ4OTE4NX0.g38JmTr35Pi4l8x2iGbRCiQvofHGQDBhqwOGKxHwANw
###

# Список заказов для тренера
GET http://localhost:4000/api/coach/orders?sortPrice=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6ImNvYWNoMUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsInVzZXJOYW1lIjoi0J_QtdGC0YDQvtCyINCf0LXRgtGAIiwiaWF0IjoxNjg4NDg4OTM0LCJleHAiOjE2ODg0ODk4MzR9.NYR2mQGVw_MsSnB0PyExVD1nmUn5PqJwvxaxR4izHks
###

#  Список друзей тренера
GET http://localhost:4000/api/coach/friends/show HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6ImNvYWNoMUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsInVzZXJOYW1lIjoi0J_QtdGC0YDQvtCyINCf0LXRgtGAIiwiaWF0IjoxNjg4NDg4OTM0LCJleHAiOjE2ODg0ODk4MzR9.NYR2mQGVw_MsSnB0PyExVD1nmUn5PqJwvxaxR4izHks
Content-Type: application/json
###

#  Удалиться из списка друзей
POST http://localhost:4000/api/coach/friends/delete/649809159b59277aa0c615a7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6ImNvYWNoMUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsInVzZXJOYW1lIjoi0J_QtdGC0YDQvtCyINCf0LXRgtGAIiwiaWF0IjoxNjg4NDg4OTM0LCJleHAiOjE2ODg0ODk4MzR9.NYR2mQGVw_MsSnB0PyExVD1nmUn5PqJwvxaxR4izHks
Content-Type: application/json
###
