# Тестовые данные
POST http://localhost:3334/api/training/test HTTP/1.1
Content-Type: application/json

{
  "training1": {"_id":"64a406e9c4d605ea3e822df6", "title": "Тренировка 1 йога", "level": "любитель","trainingStyle": "йога", "trainingTime": "10-30 мин",
                 "price": 2000, "caloriesLoss": 3000, "description": "йога для любителей", "gender": "none", "isSpecial": true,
                 "coachId": "6497fd0eaaa5a02715264c9b", "rating": 3},
  "training2": { "_id":"64a406e9c4d605ea3e822df8", "title": "Тренировка 2 аэробика", "level": "любитель","trainingStyle": "аэробика", "trainingTime": "10-30 мин",
                 "price": 1000, "caloriesLoss": 2000, "description": "аэробика для любителей", "gender": "female", "isSpecial": true,
                 "coachId": "6497fd0eaaa5a02715264c9b", "rating": 0},
  "training3": { "_id":"64a406e9c4d605ea3e822dfa", "title": "Тренировка 3 стрейчинг", "level": "новичок","trainingStyle": "стрейчинг", "trainingTime": "80-100 мин",
                 "price": 1500, "caloriesLoss": 1000, "description": "стрейчинг для новичков", "gender": "female", "isSpecial": true,
                 "coachId": "649866f6dac052e861589f59", "rating": 5},
  "training4": { "_id":"64a406e9c4d605ea3e822dfc", "title": "Тренировка 4 бег", "level": "профессионал","trainingStyle": "бег", "trainingTime": "80-100 мин",
                 "price": 1500, "caloriesLoss": 1000, "description": "бег для профессионалов", "gender": "male", "isSpecial": true,
                 "coachId": "649866f6dac052e861589f59", "rating": 0},
  "training5": { "_id":"64a406e9c4d605ea3e822dfe", "title": "Тренировка 5 йога", "level": "профессионал","trainingStyle": "йога", "trainingTime": "10-30 мин",
                 "price": 1500, "caloriesLoss": 1000, "description": "йога для профессионалов", "gender": "female", "isSpecial": true,
                 "coachId": "649866f6dac052e861589f59", "rating": 0}
}

###
